all: build

build:
	g++ -Wall -g -o server server.cpp
	g++ -Wall -g -o subscriber subscriber.cpp

server:   
	g++ -Wall -g -o server server.cpp

subscriber:      
	g++ -Wall -g -o subscriber subscriber.cpp

clean:		 
	rm -f server
	rm -f subscriber